/*
  OPTIONS:
  The following options are available for Component examples:
    - No Padding variant (noPadding: true)
    - Dark Background variant (darkBackground: true)

  Example:
    ```
      examples: [{
        name: 'Default styling',
        component: (
          <Component>Lorem ipsum</Component>
        ),
        options: {
          padding: '1rem',
          background: 'path/or/url/to/image(.jpg|.gif|.png|.svg)',
          brightness: 0.5,
        }
      },
    ```
*/

import { Tabs, Tabs__section } from './Tabs';
import docs from '!!docgen-loader?htmlDescription!./Tabs';

export default [{
  docs,
  examples: [
    {
      name: 'Align top, justify left (default)',
      component: (
        <Tabs defaultTab="0" variant="outline">
          <Tabs__section title="Tab one" >
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dolor sodales, pellentesque sapien sit amet, suscipit nulla. Nam elit nisi, posuere nec lacus vitae, mollis aliquam nisi. Cras accumsan bibendum mattis. Praesent id orci id tortor posuere convallis et id eros. Integer commodo odio dolor, ac cursus orci gravida a. Nullam nec enim id augue pretium rutrum ut ut lorem. Pellentesque ac lectus hendrerit, egestas orci non, sollicitudin purus. Donec commodo ultricies erat, at tempus elit malesuada nec. Morbi nec tempor felis.</p>
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
          </Tabs__section>
          <Tabs__section title="Tab two">
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
          </Tabs__section>
          <Tabs__section title="Tab three">
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
            <p>Nunc lacinia justo id magna consectetur suscipit. Praesent fermentum nisl vel mauris venenatis venenatis. Aenean dignissim in est vitae auctor. Pellentesque vestibulum ipsum quam, ut faucibus massa malesuada sed. Sed congue quis mauris eu rutrum. Maecenas eu viverra neque, non efficitur justo. Sed nibh massa, malesuada elementum egestas mattis, aliquet et ipsum.</p>
          </Tabs__section>
        </Tabs>
      ),
      notes: ''
    }, {
      name: 'Align top, justify center',
      component: (
        <Tabs justify="center" defaultTab="0" variant="outline">
          <Tabs__section title="Tab one" >
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dolor sodales, pellentesque sapien sit amet, suscipit nulla. Nam elit nisi, posuere nec lacus vitae, mollis aliquam nisi. Cras accumsan bibendum mattis. Praesent id orci id tortor posuere convallis et id eros. Integer commodo odio dolor, ac cursus orci gravida a. Nullam nec enim id augue pretium rutrum ut ut lorem. Pellentesque ac lectus hendrerit, egestas orci non, sollicitudin purus. Donec commodo ultricies erat, at tempus elit malesuada nec. Morbi nec tempor felis.</p>
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
          </Tabs__section>
          <Tabs__section title="Tab two">
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
          </Tabs__section>
          <Tabs__section title="Tab three">
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
            <p>Nunc lacinia justo id magna consectetur suscipit. Praesent fermentum nisl vel mauris venenatis venenatis. Aenean dignissim in est vitae auctor. Pellentesque vestibulum ipsum quam, ut faucibus massa malesuada sed. Sed congue quis mauris eu rutrum. Maecenas eu viverra neque, non efficitur justo. Sed nibh massa, malesuada elementum egestas mattis, aliquet et ipsum.</p>
          </Tabs__section>                    
        </Tabs>
      ),
      notes: ''
    }, {
      name: 'Align top, justify right',
      component: (
        <Tabs justify="right" defaultTab="0" variant="outline">
          <Tabs__section title="Tab one" >
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dolor sodales, pellentesque sapien sit amet, suscipit nulla. Nam elit nisi, posuere nec lacus vitae, mollis aliquam nisi. Cras accumsan bibendum mattis. Praesent id orci id tortor posuere convallis et id eros. Integer commodo odio dolor, ac cursus orci gravida a. Nullam nec enim id augue pretium rutrum ut ut lorem. Pellentesque ac lectus hendrerit, egestas orci non, sollicitudin purus. Donec commodo ultricies erat, at tempus elit malesuada nec. Morbi nec tempor felis.</p>
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
          </Tabs__section>
          <Tabs__section title="Tab two">
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
          </Tabs__section>
          <Tabs__section title="Tab three">
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
            <p>Nunc lacinia justo id magna consectetur suscipit. Praesent fermentum nisl vel mauris venenatis venenatis. Aenean dignissim in est vitae auctor. Pellentesque vestibulum ipsum quam, ut faucibus massa malesuada sed. Sed congue quis mauris eu rutrum. Maecenas eu viverra neque, non efficitur justo. Sed nibh massa, malesuada elementum egestas mattis, aliquet et ipsum.</p>
          </Tabs__section>                    
        </Tabs>
      ),
      notes: ''
    }, {
      name: 'Align bottom, justify left',
      component: (
        <Tabs align="bottom" defaultTab="0" variant="outline">
          <Tabs__section title="Tab one">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dolor sodales, pellentesque sapien sit amet, suscipit nulla. Nam elit nisi, posuere nec lacus vitae, mollis aliquam nisi. Cras accumsan bibendum mattis. Praesent id orci id tortor posuere convallis et id eros. Integer commodo odio dolor, ac cursus orci gravida a. Nullam nec enim id augue pretium rutrum ut ut lorem. Pellentesque ac lectus hendrerit, egestas orci non, sollicitudin purus. Donec commodo ultricies erat, at tempus elit malesuada nec. Morbi nec tempor felis.</p>
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
          </Tabs__section>
          <Tabs__section title="Tab two">
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
          </Tabs__section>
          <Tabs__section title="Tab three">
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
            <p>Nunc lacinia justo id magna consectetur suscipit. Praesent fermentum nisl vel mauris venenatis venenatis. Aenean dignissim in est vitae auctor. Pellentesque vestibulum ipsum quam, ut faucibus massa malesuada sed. Sed congue quis mauris eu rutrum. Maecenas eu viverra neque, non efficitur justo. Sed nibh massa, malesuada elementum egestas mattis, aliquet et ipsum.</p>
          </Tabs__section>                    
        </Tabs>
      ),
      notes: ''
    }, {
      name: 'Align bottom, justify center',
      component: (
        <Tabs align="bottom" justify="center" defaultTab="0" variant="outline">
          <Tabs__section title="Tab one">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dolor sodales, pellentesque sapien sit amet, suscipit nulla. Nam elit nisi, posuere nec lacus vitae, mollis aliquam nisi. Cras accumsan bibendum mattis. Praesent id orci id tortor posuere convallis et id eros. Integer commodo odio dolor, ac cursus orci gravida a. Nullam nec enim id augue pretium rutrum ut ut lorem. Pellentesque ac lectus hendrerit, egestas orci non, sollicitudin purus. Donec commodo ultricies erat, at tempus elit malesuada nec. Morbi nec tempor felis.</p>
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
          </Tabs__section>
          <Tabs__section title="Tab two">
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
          </Tabs__section>
          <Tabs__section title="Tab three">
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
            <p>Nunc lacinia justo id magna consectetur suscipit. Praesent fermentum nisl vel mauris venenatis venenatis. Aenean dignissim in est vitae auctor. Pellentesque vestibulum ipsum quam, ut faucibus massa malesuada sed. Sed congue quis mauris eu rutrum. Maecenas eu viverra neque, non efficitur justo. Sed nibh massa, malesuada elementum egestas mattis, aliquet et ipsum.</p>
          </Tabs__section>                    
        </Tabs>
      ),
      notes: ''
    }, {
      name: 'Align bottom, justify right',
      component: (
        <Tabs align="bottom" justify="right" defaultTab="0" variant="outline">
          <Tabs__section title="Tab one">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dolor sodales, pellentesque sapien sit amet, suscipit nulla. Nam elit nisi, posuere nec lacus vitae, mollis aliquam nisi. Cras accumsan bibendum mattis. Praesent id orci id tortor posuere convallis et id eros. Integer commodo odio dolor, ac cursus orci gravida a. Nullam nec enim id augue pretium rutrum ut ut lorem. Pellentesque ac lectus hendrerit, egestas orci non, sollicitudin purus. Donec commodo ultricies erat, at tempus elit malesuada nec. Morbi nec tempor felis.</p>
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
          </Tabs__section>
          <Tabs__section title="Tab two">
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
          </Tabs__section>
          <Tabs__section title="Tab three">
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
            <p>Nunc lacinia justo id magna consectetur suscipit. Praesent fermentum nisl vel mauris venenatis venenatis. Aenean dignissim in est vitae auctor. Pellentesque vestibulum ipsum quam, ut faucibus massa malesuada sed. Sed congue quis mauris eu rutrum. Maecenas eu viverra neque, non efficitur justo. Sed nibh massa, malesuada elementum egestas mattis, aliquet et ipsum.</p>
          </Tabs__section>                    
        </Tabs>
      ),
      notes: ''
    }, {
      name: 'Align left',
      component: (
        <Tabs align="left" variant="outline">
          <Tabs__section title="Tab one">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dolor sodales, pellentesque sapien sit amet, suscipit nulla. Nam elit nisi, posuere nec lacus vitae, mollis aliquam nisi. Cras accumsan bibendum mattis. Praesent id orci id tortor posuere convallis et id eros. Integer commodo odio dolor, ac cursus orci gravida a. Nullam nec enim id augue pretium rutrum ut ut lorem. Pellentesque ac lectus hendrerit, egestas orci non, sollicitudin purus. Donec commodo ultricies erat, at tempus elit malesuada nec. Morbi nec tempor felis.</p>
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
          </Tabs__section>
          <Tabs__section title="Tab two">
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
          </Tabs__section>
          <Tabs__section title="Tab three">
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
            <p>Nunc lacinia justo id magna consectetur suscipit. Praesent fermentum nisl vel mauris venenatis venenatis. Aenean dignissim in est vitae auctor. Pellentesque vestibulum ipsum quam, ut faucibus massa malesuada sed. Sed congue quis mauris eu rutrum. Maecenas eu viverra neque, non efficitur justo. Sed nibh massa, malesuada elementum egestas mattis, aliquet et ipsum.</p>
          </Tabs__section>                    
        </Tabs>
      ),
      notes: ''
    }, {
      name: 'Align left, Justify Bottom',
      component: (
        <Tabs align="left" justify="bottom" variant="outline">
          <Tabs__section title="Tab one">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dolor sodales, pellentesque sapien sit amet, suscipit nulla. Nam elit nisi, posuere nec lacus vitae, mollis aliquam nisi. Cras accumsan bibendum mattis. Praesent id orci id tortor posuere convallis et id eros. Integer commodo odio dolor, ac cursus orci gravida a. Nullam nec enim id augue pretium rutrum ut ut lorem. Pellentesque ac lectus hendrerit, egestas orci non, sollicitudin purus. Donec commodo ultricies erat, at tempus elit malesuada nec. Morbi nec tempor felis.</p>
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
          </Tabs__section>
          <Tabs__section title="Tab two">
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
          </Tabs__section>
          <Tabs__section title="Tab three">
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
            <p>Nunc lacinia justo id magna consectetur suscipit. Praesent fermentum nisl vel mauris venenatis venenatis. Aenean dignissim in est vitae auctor. Pellentesque vestibulum ipsum quam, ut faucibus massa malesuada sed. Sed congue quis mauris eu rutrum. Maecenas eu viverra neque, non efficitur justo. Sed nibh massa, malesuada elementum egestas mattis, aliquet et ipsum.</p>
          </Tabs__section>                    
        </Tabs>
      ),
      notes: ''
    }, {
      name: 'Align right',
      component: (
        <Tabs align="right" variant="outline">
          <Tabs__section title="Tab one">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dolor sodales, pellentesque sapien sit amet, suscipit nulla. Nam elit nisi, posuere nec lacus vitae, mollis aliquam nisi. Cras accumsan bibendum mattis. Praesent id orci id tortor posuere convallis et id eros. Integer commodo odio dolor, ac cursus orci gravida a. Nullam nec enim id augue pretium rutrum ut ut lorem. Pellentesque ac lectus hendrerit, egestas orci non, sollicitudin purus. Donec commodo ultricies erat, at tempus elit malesuada nec. Morbi nec tempor felis.</p>
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
          </Tabs__section>
          <Tabs__section title="Tab two">
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
          </Tabs__section>
          <Tabs__section title="Tab three">
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
            <p>Nunc lacinia justo id magna consectetur suscipit. Praesent fermentum nisl vel mauris venenatis venenatis. Aenean dignissim in est vitae auctor. Pellentesque vestibulum ipsum quam, ut faucibus massa malesuada sed. Sed congue quis mauris eu rutrum. Maecenas eu viverra neque, non efficitur justo. Sed nibh massa, malesuada elementum egestas mattis, aliquet et ipsum.</p>
          </Tabs__section>                    
        </Tabs>
      ),
      notes: ''
    }, {
      name: 'Align right, justify bottom',
      component: (
        <Tabs align="right" justify="bottom" variant="outline">
          <Tabs__section title="Tab one">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dolor sodales, pellentesque sapien sit amet, suscipit nulla. Nam elit nisi, posuere nec lacus vitae, mollis aliquam nisi. Cras accumsan bibendum mattis. Praesent id orci id tortor posuere convallis et id eros. Integer commodo odio dolor, ac cursus orci gravida a. Nullam nec enim id augue pretium rutrum ut ut lorem. Pellentesque ac lectus hendrerit, egestas orci non, sollicitudin purus. Donec commodo ultricies erat, at tempus elit malesuada nec. Morbi nec tempor felis.</p>
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
          </Tabs__section>
          <Tabs__section title="Tab two">
            <p>Fusce faucibus dolor lacus, quis iaculis nunc porta eget. Cras interdum ultricies magna, sed pharetra mauris pulvinar ac. In odio velit, egestas non tincidunt et, accumsan et sem. Etiam et augue erat. Nam a tincidunt nibh, eget vehicula massa. Cras nec odio quis velit rutrum convallis sit amet nec diam. In nulla risus, pellentesque vel erat ut, condimentum aliquam urna. Morbi purus purus, consectetur at lacus vestibulum, dictum laoreet enim. Duis posuere urna dolor, sit amet auctor ex imperdiet in.</p>
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
          </Tabs__section>
          <Tabs__section title="Tab three">
            <p>Curabitur gravida lorem a hendrerit porta. Ut ullamcorper nisl nec elit vestibulum tristique. Duis a facilisis metus, eget facilisis neque. Etiam pulvinar ligula non enim rhoncus, nec congue nisl elementum. Aliquam et lorem ac nibh pulvinar sollicitudin quis eget nisi. Duis consectetur feugiat ornare. Proin quis augue velit. Donec posuere leo ac lorem placerat ultricies. Donec placerat hendrerit est, id sodales odio accumsan nec. Morbi aliquet, eros suscipit imperdiet mollis, est ipsum tempus purus, in egestas quam eros eget nunc. Maecenas varius, enim id lobortis laoreet, lorem leo ornare dui, venenatis ultrices tellus nulla non risus.</p>
            <p>Sed dolor massa, iaculis in sodales sit amet, fringilla eget metus. Fusce vel nunc dolor. Sed sed dapibus nulla. Phasellus ornare tellus id tellus venenatis luctus. Nam mattis fermentum aliquam. Ut facilisis eros eget tempor molestie. Praesent ut luctus dui, vel volutpat quam. Donec euismod placerat viverra. Etiam mattis quam tellus, vel feugiat orci porttitor volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam placerat nulla ut dictum rutrum. Maecenas ut neque aliquam, fermentum lacus eget, luctus odio. Cras nec fermentum magna. Phasellus facilisis iaculis vehicula. Proin sed magna lacus. Aenean aliquam neque eget nisl tristique, vel consectetur dolor ullamcorper.</p>
            <p>Nunc lacinia justo id magna consectetur suscipit. Praesent fermentum nisl vel mauris venenatis venenatis. Aenean dignissim in est vitae auctor. Pellentesque vestibulum ipsum quam, ut faucibus massa malesuada sed. Sed congue quis mauris eu rutrum. Maecenas eu viverra neque, non efficitur justo. Sed nibh massa, malesuada elementum egestas mattis, aliquet et ipsum.</p>
          </Tabs__section>                    
        </Tabs>
      ),
      notes: ''
    }
  ]
}];
